Performing system checks...

System check identified no issues (0 silenced).
November 19, 2024 - 06:10:30
Django version 4.2.16, using settings 'ScriptRepo.settings'
Starting development server at http://127.0.0.1:13104/
Quit the server with CTRL-BREAK.

[19/Nov/2024 06:10:32] "GET /ScriptRepository/about/ HTTP/1.1" 200 52
Performing system checks...

System check identified no issues (0 silenced).
November 19, 2024 - 06:13:22
Django version 4.2.16, using settings 'ScriptRepo.settings'
Starting development server at http://127.0.0.1:13104/
Quit the server with CTRL-BREAK.

[19/Nov/2024 06:13:27] "GET /ScriptRepository/about/ HTTP/1.1" 200 52
Performing system checks...

System check identified no issues (0 silenced).
November 19, 2024 - 06:18:13
Django version 4.2.16, using settings 'ScriptRepo.settings'
Starting development server at http://127.0.0.1:13104/
Quit the server with CTRL-BREAK.

Performing system checks...

System check identified no issues (0 silenced).
November 19, 2024 - 06:19:55
Django version 4.2.16, using settings 'ScriptRepo.settings'
Starting development server at http://127.0.0.1:13104/
Quit the server with CTRL-BREAK.

Performing system checks...

System check identified no issues (0 silenced).
November 19, 2024 - 06:20:33
Django version 4.2.16, using settings 'ScriptRepo.settings'
Starting development server at http://127.0.0.1:13104/
Quit the server with CTRL-BREAK.

[19/Nov/2024 06:22:27] "GET /ScriptRepository/check_smtp/ HTTP/1.1" 200 54
Performing system checks...

System check identified no issues (0 silenced).
November 19, 2024 - 06:25:08
Django version 4.2.16, using settings 'ScriptRepo.settings'
Starting development server at http://127.0.0.1:13104/
Quit the server with CTRL-BREAK.

Performing system checks...

System check identified no issues (0 silenced).
November 19, 2024 - 06:25:12
Django version 4.2.16, using settings 'ScriptRepo.settings'
Starting development server at http://127.0.0.1:13104/
Quit the server with CTRL-BREAK.

Performing system checks...

System check identified no issues (0 silenced).
November 19, 2024 - 06:25:46
Django version 4.2.16, using settings 'ScriptRepo.settings'
Starting development server at http://127.0.0.1:13104/
Quit the server with CTRL-BREAK.

Performing system checks...

System check identified no issues (0 silenced).
November 19, 2024 - 06:27:17
Django version 4.2.16, using settings 'ScriptRepo.settings'
Starting development server at http://127.0.0.1:13104/
Quit the server with CTRL-BREAK.

Performing system checks...

System check identified no issues (0 silenced).
November 19, 2024 - 06:27:40
Django version 4.2.16, using settings 'ScriptRepo.settings'
Starting development server at http://127.0.0.1:13104/
Quit the server with CTRL-BREAK.

Performing system checks...

System check identified no issues (0 silenced).
November 19, 2024 - 06:29:58
Django version 4.2.16, using settings 'ScriptRepo.settings'
Starting development server at http://127.0.0.1:13104/
Quit the server with CTRL-BREAK.

Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Python313\Lib\threading.py", line 1041, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "C:\Python313\Lib\threading.py", line 992, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python313\Lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
    ~~^^^^^^^^^^^^^^^^^
  File "C:\Python313\Lib\site-packages\django\core\management\commands\runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python313\Lib\site-packages\django\core\management\base.py", line 485, in check
    all_issues = checks.run_checks(
        app_configs=app_configs,
    ...<2 lines>...
        databases=databases,
    )
  File "C:\Python313\Lib\site-packages\django\core\checks\registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "C:\Python313\Lib\site-packages\django\core\checks\urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "C:\Python313\Lib\site-packages\django\core\checks\urls.py", line 24, in check_resolver
    return check_method()
  File "C:\Python313\Lib\site-packages\django\urls\resolvers.py", line 494, in check
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "C:\Python313\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Python313\Lib\site-packages\django\urls\resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Python313\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Python313\Lib\site-packages\django\urls\resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\inetpub\wwwroot\ScriptRepo\ScriptRepo\ScriptRepo\urls.py", line 37, in <module>
    path('ScriptRepository/', include('blog.urls')),
                              ~~~~~~~^^^^^^^^^^^^^
  File "C:\Python313\Lib\site-packages\django\urls\conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\inetpub\wwwroot\ScriptRepo\ScriptRepo\blog\urls.py", line 2, in <module>
    from .views import (
    ...<6 lines>...
    )
  File "C:\inetpub\wwwroot\ScriptRepo\ScriptRepo\blog\views.py", line 16, in <module>
    from smtplib import smtp
ImportError: cannot import name 'smtp' from 'smtplib' (C:\Python313\Lib\smtplib.py)
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Python313\Lib\threading.py", line 1041, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "C:\Python313\Lib\threading.py", line 992, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python313\Lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
    ~~^^^^^^^^^^^^^^^^^
  File "C:\Python313\Lib\site-packages\django\core\management\commands\runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python313\Lib\site-packages\django\core\management\base.py", line 485, in check
    all_issues = checks.run_checks(
        app_configs=app_configs,
    ...<2 lines>...
        databases=databases,
    )
  File "C:\Python313\Lib\site-packages\django\core\checks\registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "C:\Python313\Lib\site-packages\django\core\checks\urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "C:\Python313\Lib\site-packages\django\core\checks\urls.py", line 24, in check_resolver
    return check_method()
  File "C:\Python313\Lib\site-packages\django\urls\resolvers.py", line 494, in check
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "C:\Python313\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Python313\Lib\site-packages\django\urls\resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Python313\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Python313\Lib\site-packages\django\urls\resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\inetpub\wwwroot\ScriptRepo\ScriptRepo\ScriptRepo\urls.py", line 37, in <module>
    path('ScriptRepository/', include('blog.urls')),
                              ~~~~~~~^^^^^^^^^^^^^
  File "C:\Python313\Lib\site-packages\django\urls\conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Python313\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\inetpub\wwwroot\ScriptRepo\ScriptRepo\blog\urls.py", line 2, in <module>
    from .views import (
    ...<6 lines>...
    )
  File "C:\inetpub\wwwroot\ScriptRepo\ScriptRepo\blog\views.py", line 16, in <module>
    from smtplib import smtp
ImportError: cannot import name 'smtp' from 'smtplib' (C:\Python313\Lib\smtplib.py)
Performing system checks...

System check identified no issues (0 silenced).
November 19, 2024 - 06:39:49
Django version 4.2.16, using settings 'ScriptRepo.settings'
Starting development server at http://127.0.0.1:13104/
Quit the server with CTRL-BREAK.

Performing system checks...

System check identified no issues (0 silenced).
November 19, 2024 - 06:40:33
Django version 4.2.16, using settings 'ScriptRepo.settings'
Starting development server at http://127.0.0.1:13104/
Quit the server with CTRL-BREAK.

Performing system checks...

System check identified no issues (0 silenced).
November 19, 2024 - 06:41:03
Django version 4.2.16, using settings 'ScriptRepo.settings'
Starting development server at http://127.0.0.1:13104/
Quit the server with CTRL-BREAK.

