[24/Jan/2025 06:03:22] "GET /ScriptRepository/ HTTP/1.1" 200 46452
[24/Jan/2025 06:03:24] "GET /ScriptRepository/logout/ HTTP/1.1" 405 0
Performing system checks...

System check identified no issues (0 silenced).
January 24, 2025 - 06:03:22
Django version 5.1.3, using settings 'ScriptRepo.settings'
Starting development server at http://127.0.0.1:21122/
Quit the server with CTRL-BREAK.

Traceback (most recent call last):
  File "C:\inetpub\wwwroot\ScriptRepo\ScriptRepo\manage.py", line 11, in main
    from django.core.management import execute_from_command_line
  File "C:\inetpub\wwwroot\ScriptRepo\.venv\Lib\site-packages\django\__init__.py", line 1, in <module>
    from django.utils.version import get_version
ModuleNotFoundError: No module named 'django.utils'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\inetpub\wwwroot\ScriptRepo\ScriptRepo\manage.py", line 22, in <module>
    main()
    ~~~~^^
  File "C:\inetpub\wwwroot\ScriptRepo\ScriptRepo\manage.py", line 13, in main
    raise ImportError(
    ...<3 lines>...
    ) from exc
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
